name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx tsc -v && node -v && npm -v
      - run: npx tsc --noEmit --pretty false --showConfig -p tsconfig.json
      - run: npx tsc --noEmit --pretty false -p tsconfig.json
      - run: npx tsc --noEmit --pretty false -p tests/tsconfig.json

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: lint
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm test
